version: '3.8'

services:
  sensor-logger:
    build: .
    container_name: cyber-cactus-logger
    restart: always
    network_mode: host
    volumes:
      - ./logs:/app/logs
      - ./sensor_log.csv:/app/sensor_log.csv
    environment:
      - PYTHONUNBUFFERED=1

  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: cyber-cactus-bot
    restart: always
    network_mode: host
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
    

networks:
  sensor-network:
    driver: bridge 